### ISSUE TITLE
Error by creating an entry

### ISSUE THREAD

**Issue by alexanderloewe** [ryssbowh/craft-activity#11]
Hello,

When creating a new entry, unfortunately this error occurs, in connection with the plugin craft activity.

As soon as I remove the plugin craft activity, everything works again as usual.

```
System Infos:
PHP version	8.1.14
OS version	FreeBSD 12.4-RELEASE
Database driver & version	MySQL 10.3.36
Image driver & version	Imagick 3.7.0 (ImageMagick 7.1.0-57)
Craft edition & version	Craft Pro 4.3.6.1
Yii version	2.0.47
Twig version	v3.4.3
Guzzle version	7.5.0


Plug-ins
Architect	4.0.0
Minify	4.0.0-beta.2
Neo	3.5.16
No-Cache	3.0.0
Redactor	3.0.3
Redirect Manager	2.0.0
SEOMate	2.0.3
Wheel Form	3.1.5
````

```
yii\base\UnknownPropertyException: Getting unknown property: craft\fieldlayoutelements\Heading::field in /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /home/inecehes/www/weiterwirken/v1/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Neo.php(174): yii\base\Component->__get('field')
#1 /home/inecehes/www/weiterwirken/v1/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Neo.php(158): Ryssbowh\Activity\models\fieldHandlers\elements\Neo->buildBlockValues(Object(benf\neo\elements\Block))
#2 /home/inecehes/www/weiterwirken/v1/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Neo.php(26): Ryssbowh\Activity\models\fieldHandlers\elements\Neo->buildValues()
#3 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/BaseObject.php(109): Ryssbowh\Activity\models\fieldHandlers\elements\Neo->init()
#4 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#5 /home/inecehes/www/weiterwirken/v1/vendor/ryssbowh/craft-activity/src/traits/ElementFields.php(65): craft\base\Model->__construct(Array)
#6 /home/inecehes/www/weiterwirken/v1/vendor/ryssbowh/craft-activity/src/recorders/Entries.php(116): Ryssbowh\Activity\base\recorders\ElementsRecorder->getCustomFieldValues(Object(craft\elements\Entry))
#7 /home/inecehes/www/weiterwirken/v1/vendor/ryssbowh/craft-activity/src/base/recorders/ElementsRecorder.php(66): Ryssbowh\Activity\recorders\Entries->getFieldsValues(Object(craft\elements\Entry))
#8 /home/inecehes/www/weiterwirken/v1/vendor/ryssbowh/craft-activity/src/recorders/Entries.php(52): Ryssbowh\Activity\base\recorders\ElementsRecorder->onSaved(Object(craft\elements\Entry))
#9 [internal function]: Ryssbowh\Activity\recorders\Entries->Ryssbowh\Activity\recorders\{closure}(Object(craft\events\ModelEvent))
#10 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ModelEvent))
#11 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\elements\\...', 'afterSave', Object(craft\events\ModelEvent))
#12 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/base/Element.php(4735): yii\base\Component->trigger('afterSave', Object(craft\events\ModelEvent))
#13 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/elements/Entry.php(1958): craft\base\Element->afterSave(true)
#14 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/services/Elements.php(2999): craft\elements\Entry->afterSave(true)
#15 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/services/Elements.php(1506): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, false, true, Array)
#16 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/controllers/ElementsController.php(979): craft\services\Elements->duplicateElement(Object(craft\elements\Entry))
#17 [internal function]: craft\controllers\ElementsController->actionDuplicate()
#18 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#20 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('duplicate', Array)
#21 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/duplic...', Array)
#22 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('elements/duplic...', Array)
#23 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /home/inecehes/www/weiterwirken/v1/web/index.php(23): yii\base\Application->run()
#26 {main}



Next yii\web\ServerErrorHttpException: An error occurred when duplicating the element. in /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/controllers/ElementsController.php:985
Stack trace:
#0 [internal function]: craft\controllers\ElementsController->actionDuplicate()
#1 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#3 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('duplicate', Array)
#4 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/duplic...', Array)
#5 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('elements/duplic...', Array)
#6 /home/inecehes/www/weiterwirken/v1/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /home/inecehes/www/weiterwirken/v1/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /home/inecehes/www/weiterwirken/v1/web/index.php(23): yii\base\Application->run()
#9 {main}```

**Comment by ryssbowh** [comment]
Hi,

This has been fixed in 2.3.3
