### ISSUE TITLE
[BUG] Error while saving entries with neo fields

### ISSUE THREAD

**Issue by mihob** [ryssbowh/craft-activity#17]
The following Bug occurs when saving entries with neo fields, it doesent always happen

TypeError
Ryssbowh\Activity\base\fieldHandlers\FieldHandler::getDirty(): Argument #1 ($handler) must be of type Ryssbowh\Activity\base\fieldHandlers\FieldHandler, null given, called in /app/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Neo.php on line 109

Stacktrace:
```
#26 /app/vendor/ryssbowh/craft-activity/src/base/fieldHandlers/FieldHandler.php(44): Ryssbowh\Activity\base\fieldHandlers\FieldHandler::getDirty
#25 /app/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Neo.php(109): Ryssbowh\Activity\models\fieldHandlers\elements\Neo::buildDirtyBlocks
#24 /app/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Neo.php(89): Ryssbowh\Activity\models\fieldHandlers\elements\Neo::buildDirty
#23 /app/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Neo.php(36): Ryssbowh\Activity\models\fieldHandlers\elements\Neo::getDirty
#22 /app/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Neo.php(46): Ryssbowh\Activity\models\fieldHandlers\elements\Neo::isDirty
#21 /app/vendor/ryssbowh/craft-activity/src/traits/ElementFields.php(30): Ryssbowh\Activity\base\recorders\ElementsRecorder::getDirtyFields
#20 /app/vendor/ryssbowh/craft-activity/src/base/recorders/ElementsRecorder.php(66): Ryssbowh\Activity\base\recorders\ElementsRecorder::onSaved
#19 /app/vendor/ryssbowh/craft-activity/src/recorders/Entries.php(52): Ryssbowh\Activity\recorders\Entries::Ryssbowh\Activity\recorders\{closure}
#18 [internal](0): call_user_func
#17 /app/vendor/yiisoft/yii2/base/Event.php(312): yii\base\Event::trigger
#16 /app/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Component::trigger
#15 /app/vendor/craftcms/cms/src/base/Element.php(4993): craft\base\Element::afterSave
#14 /app/vendor/craftcms/cms/src/elements/Entry.php(1938): craft\elements\Entry::afterSave
#13 /app/vendor/craftcms/cms/src/services/Elements.php(3170): craft\services\Elements::_saveElementInternal
#12 /app/vendor/craftcms/cms/src/services/Elements.php(1549): craft\services\Elements::duplicateElement
#11 /app/vendor/craftcms/cms/src/services/Elements.php(1194): craft\services\Elements::updateCanonicalElement
#10 /app/vendor/craftcms/cms/src/services/Drafts.php(304): craft\services\Drafts::applyDraft
#9 /app/vendor/craftcms/cms/src/controllers/ElementsController.php(1337): craft\controllers\ElementsController::actionApplyDraft
#8 [internal](0): call_user_func_array
#7 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#6 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Controller::runAction
#5 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Module::runAction
#4 /app/vendor/craftcms/cms/src/web/Application.php(304): craft\web\Application::runAction
#3 /app/vendor/craftcms/cms/src/web/Application.php(607): craft\web\Application::_processActionRequest
#2 /app/vendor/craftcms/cms/src/web/Application.php(283): craft\web\Application::handleRequest
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\base\Application::run
#0 /index.php(27): null
```

Craft Version: 4.4.17
Plugin Version: 2.3.12

**Comment by ryssbowh** [comment]
Hi, this should be fixed in 2.3.13
