### ISSUE TITLE
Error creating new user

### ISSUE THREAD

**Issue by jessrezac** [ryssbowh/craft-activity#28]
When creating a new user, this error is thrown: 

```
TypeError: Ryssbowh\Activity\base\recorders\ElementsRecorder::shouldSaveElementLog(): Argument #2 ($element) must be of type craft\base\Element, null given, called in /var/www/html/vendor/ryssbowh/craft-activity/src/recorders/Users.php on line 341 and defined in /var/www/html/vendor/ryssbowh/craft-activity/src/base/recorders/ElementsRecorder.php:173
Stack trace:
#0 /var/www/html/vendor/ryssbowh/craft-activity/src/recorders/Users.php(341): Ryssbowh\Activity\base\recorders\ElementsRecorder->shouldSaveElementLog('userPermissions...', NULL)
#1 /var/www/html/vendor/ryssbowh/craft-activity/src/recorders/Users.php(376): Ryssbowh\Activity\recorders\Users->saveNewPermissions(Object(craft\web\Application))
#2 [internal function]: Ryssbowh\Activity\recorders\Users->Ryssbowh\Activity\recorders\{closure}(Object(yii\base\Event))
#3 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#4 /var/www/html/vendor/yiisoft/yii2/base/Component.php(650): yii\base\Event::trigger('yii\\base\\Applic...', 'afterRequest', Object(yii\base\Event))
#5 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(546): yii\base\Component->trigger('afterRequest', Object(yii\base\Event))
#6 /var/www/html/vendor/yiisoft/yii2/base/Application.php(387): craft\web\Application->trigger('afterRequest')
#7 /var/www/html/web/index.php(12): yii\base\Application->run()
#8 {main}
```

**Comment by ryssbowh** [comment]
Thanks for reporting, that's been fixed in 3.0.4
