### ISSUE TITLE
Error after entry save

### ISSUE THREAD

**Issue by wmdhosting** [ryssbowh/craft-activity#5]
Found one more.. 

```
TypeError: Ryssbowh\Activity\models\fieldHandlers\elements\SuperTable::buildDirty(): Argument #2 ($oldBlocks) must be of type array, null given, called in /home/devkorisnik/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/SuperTable.php on line 31 and defined in /home/devkorisnik/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/SuperTable.php:80
Stack trace:
#0 /home/devkorisnik/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/SuperTable.php(31): Ryssbowh\Activity\models\fieldHandlers\elements\SuperTable->buildDirty(Array, NULL)
#1 /home/devkorisnik/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Matrix.php(91): Ryssbowh\Activity\models\fieldHandlers\elements\SuperTable->getDirty(Object(Ryssbowh\Activity\models\fieldHandlers\elements\Entries))
#2 /home/devkorisnik/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Matrix.php(32): Ryssbowh\Activity\models\fieldHandlers\elements\Matrix->buildDirty(Array, Array)
#3 /home/devkorisnik/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/elements/Matrix.php(42): Ryssbowh\Activity\models\fieldHandlers\elements\Matrix->getDirty(Object(Ryssbowh\Activity\models\fieldHandlers\elements\Matrix))
#4 /home/devkorisnik/vendor/ryssbowh/craft-activity/src/traits/ElementFields.php(30): Ryssbowh\Activity\models\fieldHandlers\elements\Matrix->isDirty(Object(Ryssbowh\Activity\models\fieldHandlers\elements\Matrix))
#5 /home/devkorisnik/vendor/ryssbowh/craft-activity/src/base/recorders/ElementsRecorder.php(66): Ryssbowh\Activity\base\recorders\ElementsRecorder->getDirtyFields(Array, Array)
#6 /home/devkorisnik/vendor/ryssbowh/craft-activity/src/recorders/Entries.php(52): Ryssbowh\Activity\base\recorders\ElementsRecorder->onSaved(Object(craft\elements\Entry))
#7 [internal function]: Ryssbowh\Activity\recorders\Entries->Ryssbowh\Activity\recorders\{closure}(Object(craft\events\ModelEvent))
#8 /home/devkorisnik/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ModelEvent))
#9 /home/devkorisnik/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\elements\\...', 'afterSave', Object(craft\events\ModelEvent))
#10 /home/devkorisnik/vendor/craftcms/cms/src/base/Element.php(4735): yii\base\Component->trigger('afterSave', Object(craft\events\ModelEvent))
#11 /home/devkorisnik/vendor/craftcms/cms/src/elements/Entry.php(1958): craft\base\Element->afterSave(false)
#12 /home/devkorisnik/vendor/craftcms/cms/src/services/Elements.php(2999): craft\elements\Entry->afterSave(false)
#13 /home/devkorisnik/vendor/craftcms/cms/src/services/Elements.php(1506): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, false, true, Array)
#14 /home/devkorisnik/vendor/craftcms/cms/src/services/Elements.php(1151): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#15 /home/devkorisnik/vendor/craftcms/cms/src/services/Drafts.php(304): craft\services\Elements->updateCanonicalElement(Object(craft\elements\Entry), Array)
#16 /home/devkorisnik/vendor/craftcms/cms/src/controllers/ElementsController.php(1322): craft\services\Drafts->applyDraft(Object(craft\elements\Entry))
#17 [internal function]: craft\controllers\ElementsController->actionApplyDraft()
#18 /home/devkorisnik/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /home/devkorisnik/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#20 /home/devkorisnik/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('apply-draft', Array)
#21 /home/devkorisnik/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/apply-...', Array)
#22 /home/devkorisnik/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('elements/apply-...', Array)
#23 /home/devkorisnik/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /home/devkorisnik/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /home/devkorisnik/public_html/index.php(24): yii\base\Application->run()
#26 {main}
```

CRAFT  4.3.4
User activity.   2.2.4

**Comment by ryssbowh** [comment]
Hi,

I can't reproduce this, what steps do you go through to get this error ?
I'm guessing you have a super table inside a matrix field ?

**Comment by wmdhosting** [comment]
Just saving entry..   yes with elemnts that have super table..

**Comment by ryssbowh** [comment]
I have tried just saving an entry with super table fields and super table fields inside matrix it all works for me.
You must do something different, have you changed anything in the field configuration before this happened ? Changing field types maybe ?
Could you maybe share your database and send it to support@puzzlers.run ?

**Comment by wmdhosting** [comment]
i got this error few days before.  
Yeastreday.. upgraded..    some supertable. fix.. 

I tryed now.. seems working OK:.
